fix: updated test code to reference local prepare-test-env-ava.js file
agoric-labs/ag-power-tools pull request #27
Opened 2024-01-22 21:44 UTC by tgrecojs

running `yarn test` from the contract directory failed to properly test launchIt and postalSvc. 

below shows what is logged to my console.

```sh
yarn run test
yarn run v1.22.19
$ ava --verbose

  Uncaught exception in test/test-launchIt.js

  AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert(refs.runnerChain)

  Uncaught exception in test/test-start1.js

  AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert(refs.runnerChain)

SES_UNHANDLED_REJECTION: (AssertionError#1)
SES_UNHANDLED_REJECTION: (AssertionError#1)
  Uncaught exception in test/test-postalSvc.js

  AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert(refs.runnerChain)

  ✘ test/test-start1.js exited with a non-zero exit code: 1
SES_UNHANDLED_REJECTION: (AssertionError#1)
  ✘ test/test-launchIt.js exited with a non-zero exit code: 1
  ✘ test/test-postalSvc.js exited with a non-zero exit code: 1
start-game1-proposal.js module evaluating

```

upon inspection, i noticed that these files referenced ava from `@agoric/zoe` whereas all other test files referenced the local version of the file, so i updated the code accordingly. now, running `yarn test` with these changes works as expected.

2024-01-22 21:48 UTC, dckc commented on contract/test/test-launchIt.js
> -
I don't see how this change is relevant. What happens if you revert it? (all 3 times)

2024-01-22 21:50 UTC, dckc requested changes
are the type changes necessary?

2024-01-22 23:03 UTC, tgrecojs commented
> are the type changes necessary?

No, they aren't. I modified the code so that they are included now. 

Let me know if anything else needs changing.

2024-01-22 23:05 UTC, dckc requested changes
one more bit to undo...

2024-01-22 23:05 UTC, dckc commented on contract/test/test-postalSvc.js
> +
put this back where it was, please?

2024-01-22 23:15 UTC, tgrecojs commented on contract/test/test-postalSvc.js
> +
@dckc should be good now 😓 🙂

2024-01-23 01:20 UTC, dckc approved these changes
thanks!

2024-01-23 01:20 UTC, merged